# CI: linting on each commit
name: lint

on:
  push:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.2.*
    - name: Install dependencies
      run: |
        poetry lock
        poetry install
    - name: Run lint command from tox.ini
      run: |
        poetry run tox -e lint
