# integration tests with pytest, runs on each commit
# additionally once per week to get a notification if the external API caused breakage

name: test

on:
  push:
  schedule:
    - cron: 0 6 * * 1

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.2.*
    - name: Install dependencies
      run: |
        poetry lock
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --capture=no
